# The Default Profile
[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer_runs = 1_000

[rpc_endpoints]
op_goerli = "${OP_GOERLI_RPC_URL}"

[etherscan]
op_goerli = { key = "${ETHERSCAN_API_KEY}" }